// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/generics.proto

package oidb

type OidbFriend struct {
	Uid        string                  `protobuf:"bytes,1,opt"`
	Uin        uint32                  `protobuf:"varint,3,opt"`
	Additional []*OidbFriendAdditional `protobuf:"bytes,10001,rep"`
}

type OidbFriendAdditional struct {
	Type   uint32            `protobuf:"varint,1,opt"`
	Layer1 *OidbFriendLayer1 `protobuf:"bytes,2,opt"`
	_      [0]func()
}

type OidbFriendLayer1 struct {
	Properties []*OidbFriendProperty `protobuf:"bytes,2,rep"`
}

type OidbFriendProperty struct {
	Code  uint32 `protobuf:"varint,1,opt"`
	Value string `protobuf:"bytes,2,opt"`
	_     [0]func()
}

type OidbLafter struct {
	Type     int32  `protobuf:"varint,1,opt"`
	D2       []byte `protobuf:"bytes,2,opt"`
	SubAppid uint32 `protobuf:"varint,3,opt"`
}

type OidbNumber struct {
	Numbers []uint32 `protobuf:"varint,1,rep"`
}

type OidbProperty struct {
	Key   string `protobuf:"bytes,1,opt"`
	Value []byte `protobuf:"bytes,2,opt"`
}

type OidbTwoNumber struct {
	Number1 uint32 `protobuf:"varint,1,opt"`
	Number2 uint32 `protobuf:"varint,2,opt"`
	_       [0]func()
}
