// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0xEB7_1.proto

package oidb

type OidbSvcTrpcTcp0XEB7_1_ReqBody struct {
	SignInWriteReq *StSignInWriteReq `protobuf:"bytes,2,opt"`
	_              [0]func()
}

type StSignInWriteReq struct {
	Uin        string `protobuf:"bytes,1,opt"`
	GroupUin   string `protobuf:"bytes,2,opt"`
	AppVersion string `protobuf:"bytes,3,opt"` // 不确定要不要加，测试过没有这个参数也是可以的
	_          [0]func()
}

type OidbSvcTrpcTcp0XEB7_1_RspBody struct {
	SignInWriteRsp *StSignInWriteRsp `protobuf:"bytes,2,opt"`
	_              [0]func()
}

type StSignInWriteRsp struct {
	DoneInfo *SignInStatusDoneInfo `protobuf:"bytes,2,opt"`
	_        [0]func()
}

type SignInStatusDoneInfo struct {
	Title       string   `protobuf:"bytes,1,opt"` // 今日已成功打卡
	KeepDayText string   `protobuf:"bytes,2,opt"` // 已打卡N天
	ClockInInfo []string `protobuf:"bytes,3,rep"` // ["群内排名第N位", "[clock in timestamp (second)]"]
	DetailUrl   string   `protobuf:"bytes,4,opt"` // https://qun.qq.com/v2/signin/detail?...
}
