// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0xEAC.proto

package oidb

// RemoveEssenceMessage
type OidbSvcTrpcTcp0XEAC struct {
	GroupUin uint32 `protobuf:"varint,1,opt"`
	Sequence uint32 `protobuf:"varint,2,opt"`
	Random   uint32 `protobuf:"varint,3,opt"`
	_        [0]func()
}
