// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x1097_1.proto

package oidb

// Quit Group
type OidbSvcTrpcTcp0X1097_1 struct {
	GroupUin uint32 `protobuf:"varint,1,opt"`
	_        [0]func()
}
