// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x10C8.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

// Accept group request
type OidbSvcTrpcTcp0X10C8 struct {
	Accept uint32                    `protobuf:"varint,1,opt"` // 2 for reject, 1 for accept, 3 for ignore
	Body   *OidbSvcTrpcTcp0X10C8Body `protobuf:"bytes,2,opt"`
	_      [0]func()
}

type OidbSvcTrpcTcp0X10C8Body struct {
	Sequence  uint64               `protobuf:"varint,1,opt"` // 1
	EventType uint32               `protobuf:"varint,2,opt"` // 2
	GroupUin  uint32               `protobuf:"varint,3,opt"` // 3
	Message   proto.Option[string] `protobuf:"bytes,4,opt"`  // ""
	_         [0]func()
}
