// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0xB5D_44.proto

package oidb

// Set Friend Request
type OidbSvcTrpcTcp0XB5D_44 struct {
	Accept    uint32 `protobuf:"varint,1,opt"` // 3 for accept, 5 for reject
	TargetUid string `protobuf:"bytes,2,opt"`
	_         [0]func()
}
