// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x126B_0.proto

package oidb

type OidbSvcTrpcTcp0X126B_0 struct {
	Field1 *OidbSvcTrpcTcp0X126B_0_Field1 `protobuf:"bytes,1,opt"`
	_      [0]func()
}

type OidbSvcTrpcTcp0X126B_0_Field1 struct {
	TargetUid string                           `protobuf:"bytes,1,opt"`
	Field2    *OidbSvcTrpcTcp0X126B_0_Field1_2 `protobuf:"bytes,2,opt"`
	Block     bool                             `protobuf:"varint,3,opt"`
	Field4    bool                             `protobuf:"varint,4,opt"` // true
	_         [0]func()
}

type OidbSvcTrpcTcp0X126B_0_Field1_2 struct {
	Field1 uint32                             `protobuf:"varint,1,opt"` // 130
	Field2 uint32                             `protobuf:"varint,2,opt"` // 109
	Field3 *OidbSvcTrpcTcp0X126B_0_Field1_2_3 `protobuf:"bytes,3,opt"`
	_      [0]func()
}

type OidbSvcTrpcTcp0X126B_0_Field1_2_3 struct {
	Field1 uint32 `protobuf:"varint,1,opt"` // 8
	Field2 uint32 `protobuf:"varint,2,opt"` // 8
	Field3 uint32 `protobuf:"varint,3,opt"` // 50
	_      [0]func()
}
