// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x8A7_0.proto

package oidb

type OidbSvcTrpcTcp0X8A7_0_ReqBody struct {
	SubCmd                    uint32 `protobuf:"varint,1,opt"`
	LimitIntervalTypeForUin   uint32 `protobuf:"varint,2,opt"`
	LimitIntervalTypeForGroup uint32 `protobuf:"varint,3,opt"`
	Uin                       uint64 `protobuf:"varint,4,opt"`
	GroupUin                  uint64 `protobuf:"varint,5,opt"`
	_                         [0]func()
}

type OidbSvcTrpcTcp0X8A7_0_RspBody struct {
	CanAtAll      bool   `protobuf:"varint,1,opt"`
	CountForUin   uint32 `protobuf:"varint,2,opt"`
	CountForGroup uint32 `protobuf:"varint,3,opt"`
	_             [0]func()
}
