// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0xFE1_2.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

// Fetch Avatar
type OidbSvcTrpcTcp0XFE1_2 struct {
	Uid    proto.Option[string]        `protobuf:"bytes,1,opt"`
	Field2 uint32                      `protobuf:"varint,2,opt"`
	Keys   []*OidbSvcTrpcTcp0XFE1_2Key `protobuf:"bytes,3,rep"`
}

type OidbSvcTrpcTcp0XFE1_2Uin struct {
	Uin    uint32                      `protobuf:"varint,1,opt"`
	Field2 uint32                      `protobuf:"varint,2,opt"`
	Keys   []*OidbSvcTrpcTcp0XFE1_2Key `protobuf:"bytes,3,rep"`
}

type OidbSvcTrpcTcp0XFE1_2Key struct {
	Key uint32 `protobuf:"varint,1,opt"`
	_   [0]func()
}

type OidbSvcTrpcTcp0XFE1_2Response struct {
	Body *OidbSvcTrpcTcp0XFE1_2ResponseBody `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type OidbSvcTrpcTcp0XFE1_2ResponseBody struct {
	// string Uid = 1;
	Properties *OidbSvcTrpcTcp0XFE1_2ResponseProperty `protobuf:"bytes,2,opt"`
	Uin        uint32                                 `protobuf:"varint,3,opt"`
	_          [0]func()
}

type OidbSvcTrpcTcp0XFE1_2ResponseProperty struct {
	NumberProperties []*OidbTwoNumber      `protobuf:"bytes,1,rep"`
	StringProperties []*OidbFriendProperty `protobuf:"bytes,2,rep"`
}
