// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x929D_0.proto

package oidb

type OidbSvcTrpcTcp0X929D_0_Req struct {
	GroupUin uint32 `protobuf:"varint,1,opt"`
	ChatType uint32 `protobuf:"varint,2,opt"` // 1 voice, 2 song
	_        [0]func()
}

type OidbSvcTrpcTcp0X929D_0_Rsp struct {
	Property []*OidbSvcTrpcTcp0X929D_0_Rsp_Key `protobuf:"bytes,1,rep"`
}

type OidbSvcTrpcTcp0X929D_0_Rsp_Key struct {
	Type  string                                 `protobuf:"bytes,1,opt"`
	Value []*OidbSvcTrpcTcp0X929D_0_Rsp_Property `protobuf:"bytes,2,rep"`
}

type OidbSvcTrpcTcp0X929D_0_Rsp_Property struct {
	CharacterId       string `protobuf:"bytes,1,opt"`
	CharacterName     string `protobuf:"bytes,2,opt"`
	CharacterVoiceUrl string `protobuf:"bytes,3,opt"`
	_                 [0]func()
}
