// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x1253_1.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

// Group Member Mute
type OidbSvcTrpcTcp0X1253_1 struct {
	GroupUin uint32                      `protobuf:"varint,1,opt"`
	Type     uint32                      `protobuf:"varint,2,opt"`
	Body     *OidbSvcTrpcTcp0X1253_1Body `protobuf:"bytes,3,opt"`
	_        [0]func()
}

type OidbSvcTrpcTcp0X1253_1Body struct {
	TargetUid string `protobuf:"bytes,1,opt"`
	Duration  uint32 `protobuf:"varint,2,opt"`
	_         [0]func()
}

type OidbSvcTrpcTcp0X1253_1Response struct {
	Success proto.Option[string] `protobuf:"bytes,2,opt"`
	_       [0]func()
}
