// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x6D7.proto

package oidb

type OidbSvcTrpcTcp0X6D7 struct {
	Create *OidbSvcTrpcTcp0X6D7Create `protobuf:"bytes,1,opt"`
	Delete *OidbSvcTrpcTcp0X6D7Delete `protobuf:"bytes,2,opt"`
	_      [0]func()
}

type OidbSvcTrpcTcp0X6D7Create struct {
	GroupUin        uint32 `protobuf:"varint,1,opt"`
	TargetDirectory string `protobuf:"bytes,3,opt"`
	FolderName      string `protobuf:"bytes,4,opt"`
	_               [0]func()
}

type OidbSvcTrpcTcp0X6D7Delete struct {
	GroupUin uint32 `protobuf:"varint,1,opt"`
	FolderId string `protobuf:"bytes,3,opt"`
	_        [0]func()
}

type OidbSvcTrpcTcp0X6D7Response struct {
	Create *OidbSvcTrpcTcp0X6D7_0Response `protobuf:"bytes,1,opt"`
	Delete *OidbSvcTrpcTcp0X6D7_1Response `protobuf:"bytes,2,opt"`
	_      [0]func()
}

type OidbSvcTrpcTcp0X6D7_1Response struct {
	RetCode       int32  `protobuf:"varint,1,opt"`
	RetMsg        string `protobuf:"bytes,2,opt"`
	ClientWording string `protobuf:"bytes,3,opt"`
	_             [0]func()
}

type OidbSvcTrpcTcp0X6D7_0Response struct {
	RetCode       int32                                    `protobuf:"varint,1,opt"`
	RetMsg        string                                   `protobuf:"bytes,2,opt"`
	ClientWording string                                   `protobuf:"bytes,3,opt"`
	FolderInfo    *OidbSvcTrpcTcp0X6D7_0ResponseFolderInfo `protobuf:"bytes,4,opt"`
	_             [0]func()
}

type OidbSvcTrpcTcp0X6D7_0ResponseFolderInfo struct {
	FolderId     string `protobuf:"bytes,1,opt"`
	FolderPath   string `protobuf:"bytes,2,opt"`
	FolderName   string `protobuf:"bytes,3,opt"`
	Timestamp4   uint32 `protobuf:"varint,4,opt"`
	Timestamp5   uint32 `protobuf:"varint,5,opt"`
	OperatorUin6 uint32 `protobuf:"varint,6,opt"`
	OperatorUin9 uint32 `protobuf:"varint,9,opt"`
	_            [0]func()
}
