// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x10C0_1.proto

package oidb

// Fetch Friends & Group Notification List
type OidbSvcTrpcTcp0X10C0_1 struct {
	Count  uint32 `protobuf:"varint,1,opt"`
	Field2 uint32 `protobuf:"varint,2,opt"`
	_      [0]func()
}

type OidbSvcTrpcTcp0X10C0_1Response struct {
	Requests     []*OidbSvcTrpcTcp0X10C0_1ResponseRequests `protobuf:"bytes,1,rep"`
	Field2       uint64                                    `protobuf:"varint,2,opt"`
	NewLatestSeq uint64                                    `protobuf:"varint,3,opt"`
	Field4       uint32                                    `protobuf:"varint,4,opt"`
	Field5       uint64                                    `protobuf:"varint,5,opt"`
	Field6       uint32                                    `protobuf:"varint,6,opt"`
}

type OidbSvcTrpcTcp0X10C0_1ResponseRequests struct {
	Sequence  uint64                               `protobuf:"varint,1,opt"`
	EventType uint32                               `protobuf:"varint,2,opt"`
	State     uint32                               `protobuf:"varint,3,opt"`
	Group     *OidbSvcTrpcTcp0X10C0_1ResponseGroup `protobuf:"bytes,4,opt"`
	Target    *OidbSvcTrpcTcp0X10C0_1ResponseUser  `protobuf:"bytes,5,opt"`
	Invitor   *OidbSvcTrpcTcp0X10C0_1ResponseUser  `protobuf:"bytes,6,opt"`
	Operator  *OidbSvcTrpcTcp0X10C0_1ResponseUser  `protobuf:"bytes,7,opt"`
	Field9    string                               `protobuf:"bytes,9,opt"`
	Comment   string                               `protobuf:"bytes,10,opt"`
	_         [0]func()
}

type OidbSvcTrpcTcp0X10C0_1ResponseGroup struct {
	GroupUin  uint32 `protobuf:"varint,1,opt"`
	GroupName string `protobuf:"bytes,2,opt"`
	_         [0]func()
}

type OidbSvcTrpcTcp0X10C0_1ResponseUser struct {
	Uid  string `protobuf:"bytes,1,opt"`
	Name string `protobuf:"bytes,2,opt"`
	_    [0]func()
}
