// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0xE37_1700.proto

package oidb

// Upload Offline File
type OidbSvcTrpcTcp0XE37_1700 struct {
	Command                  uint32            `protobuf:"varint,1,opt"` // 1700
	Seq                      int32             `protobuf:"varint,2,opt"` // 0
	Upload                   *ApplyUploadReqV3 `protobuf:"bytes,19,opt"`
	BusinessId               int32             `protobuf:"varint,101,opt"` // 3
	ClientType               int32             `protobuf:"varint,102,opt"` // 1
	FlagSupportMediaPlatform int32             `protobuf:"varint,200,opt"` // 1
	_                        [0]func()
}

type ApplyUploadReqV3 struct {
	SenderUid      string `protobuf:"bytes,10,opt"`
	ReceiverUid    string `protobuf:"bytes,20,opt"`
	FileSize       uint32 `protobuf:"varint,30,opt"`
	FileName       string `protobuf:"bytes,40,opt"`
	Md510MCheckSum []byte `protobuf:"bytes,50,opt"`
	Sha1CheckSum   []byte `protobuf:"bytes,60,opt"`
	LocalPath      string `protobuf:"bytes,70,opt"`
	Md5CheckSum    []byte `protobuf:"bytes,110,opt"`
	Sha3CheckSum   []byte `protobuf:"bytes,120,opt"`
}
