// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x102A_1.proto

package oidb

// // Fetch Client Key lwx: 我也觉得抽象 可是他真的是空的
type OidbSvcTrpcTcp0X102A_1 struct {
	_ [0]func()
}

type OidbSvcTrpcTcp0X102A_1Response struct {
	Field1     uint32 `protobuf:"varint,2,opt"`
	ClientKey  string `protobuf:"bytes,3,opt"`
	Expiration uint32 `protobuf:"varint,4,opt"`
	_          [0]func()
}
