// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0xBCB_0.proto

package oidb

type OidbSvcTrpcTcp0XBCB_0_ReqBody struct {
	NotUseCache int32        `protobuf:"varint,9,opt"`
	CheckUrlReq *CheckUrlReq `protobuf:"bytes,10,opt"`
	_           [0]func()
}

type CheckUrlReq struct {
	Url         []string `protobuf:"bytes,1,rep"`
	Refer       string   `protobuf:"bytes,2,opt"`
	Plateform   string   `protobuf:"bytes,3,opt"`
	QqPfTo      string   `protobuf:"bytes,4,opt"`
	Type        uint32   `protobuf:"varint,5,opt"`
	From        uint32   `protobuf:"varint,6,opt"`
	Chatid      uint64   `protobuf:"varint,7,opt"`
	ServiceType uint64   `protobuf:"varint,8,opt"`
	SendUin     uint64   `protobuf:"varint,9,opt"`
	ReqType     string   `protobuf:"bytes,10,opt"`
	OriginalUrl string   `protobuf:"bytes,11,opt"`
	IsArk       bool     `protobuf:"varint,12,opt"`
	ArkName     string   `protobuf:"bytes,13,opt"`
	IsFinish    bool     `protobuf:"varint,14,opt"`
	SrcUrls     []string `protobuf:"bytes,15,rep"`
	SrcPlatform uint32   `protobuf:"varint,16,opt"`
	Qua         string   `protobuf:"bytes,17,opt"`
}

type OidbSvcTrpcTcp0XBCB_0_RspBody struct {
	Wording     string       `protobuf:"bytes,1,opt"`
	CheckUrlRsp *CheckUrlRsp `protobuf:"bytes,10,opt"`
	_           [0]func()
}

type CheckUrlRsp struct {
	Results         []*UrlCheckResult `protobuf:"bytes,1,rep"`
	NextReqDuration uint32            `protobuf:"varint,2,opt"`
}

type UrlCheckResult struct {
	Url          string `protobuf:"bytes,1,opt"`
	Result       uint32 `protobuf:"varint,2,opt"`
	JumpResult   uint32 `protobuf:"varint,3,opt"`
	JumpUrl      string `protobuf:"bytes,4,opt"`
	Level        uint32 `protobuf:"varint,5,opt"`
	SubLevel     uint32 `protobuf:"varint,6,opt"`
	Umrtype      uint32 `protobuf:"varint,7,opt"`
	RetFrom      uint32 `protobuf:"varint,8,opt"`
	OperationBit uint64 `protobuf:"varint,9,opt"`
	_            [0]func()
}
