// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/message/routing.proto

package message

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type ForwardHead struct {
	Field1        proto.Option[uint32] `protobuf:"varint,1,opt"`
	Field2        proto.Option[uint32] `protobuf:"varint,2,opt"`
	Field3        proto.Option[uint32] `protobuf:"varint,3,opt"` // for friend: 2, for group: null
	UnknownBase64 proto.Option[string] `protobuf:"bytes,5,opt"`
	Avatar        proto.Option[string] `protobuf:"bytes,6,opt"`
	_             [0]func()
}

type Grp struct {
	GroupCode proto.Option[uint32] `protobuf:"varint,1,opt"`
	_         [0]func()
}

type GrpTmp struct {
	GroupUin proto.Option[uint32] `protobuf:"varint,1,opt"`
	ToUin    proto.Option[uint32] `protobuf:"varint,2,opt"`
	_        [0]func()
}

type ResponseForward struct {
	FriendName proto.Option[string] `protobuf:"bytes,6,opt"`
	_          [0]func()
}

type ResponseGrp struct {
	GroupUin   uint32 `protobuf:"varint,1,opt"`
	MemberName string `protobuf:"bytes,4,opt"`
	GroupName  string `protobuf:"bytes,7,opt"`
	_          [0]func()
}

type Trans0X211 struct {
	ToUin proto.Option[uint64] `protobuf:"varint,1,opt"`
	CcCmd proto.Option[uint32] `protobuf:"varint,2,opt"`
	Uid   proto.Option[string] `protobuf:"bytes,8,opt"`
	_     [0]func()
}

type WPATmp struct {
	ToUin uint64 `protobuf:"varint,1,opt"`
	Sig   []byte `protobuf:"bytes,2,opt"`
}
