version: "2"
run:
  go: "1.24"
  issues-exit-code: 1
  tests: false
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - forbidigo
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - makezero
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*
    forbidigo:
      forbid:
        - pattern: ^errors\.Errorf.*$
          msg: Use fmt.Errorf with %w to replace it.
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/LagrangeDev/LagrangeGo
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
