linters-settings:
  errcheck:
    exclude-functions:
      - fmt:.*
      - io/ioutil:^Read.*

  goimports:
    local-prefixes: github.com/LagrangeDev/LagrangeGo

  forbidigo:
    forbid:
      - p: ^errors\.Errorf.*$
        msg: Use fmt.Errorf with %w to replace it.

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  fast: false
  enable:
    - bodyclose
    #- depguard
    - dogsled
    - errcheck
    - copyloopvar
    - exhaustive
    #- funlen
    #- goconst
    - gocritic
    #- gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    #- gosec
    - gosimple
    - govet
    - ineffassign
    #- misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - revive
    - forbidigo
    - makezero


run:
  # default concurrency is a available CPU number.
  # concurrency: 4 # explicitly omit this value to fully utilize available resources.
  deadline: 5m
  issues-exit-code: 1
  tests: false
  go: '1.23'

# output configuration options
output:
  formats:
    - format: "colored-line-number"
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

issues:
  # Fix found issues (if it's supported by the linter)
  fix: true
