// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x89A_0.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

// Group Global Mute
type OidbSvcTrpcTcp0X89A_0 struct {
	GroupUin uint32                      `protobuf:"varint,1,opt"`
	State    *OidbSvcTrpcTcp0X89A_0State `protobuf:"bytes,2,opt"`
	_        [0]func()
}

type OidbSvcTrpcTcp0X89A_0State struct {
	S uint32 `protobuf:"varint,17,opt"`
	_ [0]func()
}

type OidbSvcTrpcTcp0X89A_0Response struct {
	GroupUin uint32               `protobuf:"varint,1,opt"`
	ErorMsg  proto.Option[string] `protobuf:"bytes,2,opt"`
	_        [0]func()
}
