// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x7C1_1.proto

package oidb

// RequestFriendSetting
type OidbSvcTrpcTcp0X7C1_1 struct {
	Field1    uint32 `protobuf:"varint,1,opt"` // 1
	SelfUin   uint32 `protobuf:"varint,2,opt"`
	TargetUin uint32 `protobuf:"varint,3,opt"`
	Field4    uint32 `protobuf:"varint,4,opt"` // 3999
	Field5    uint32 `protobuf:"varint,5,opt"` // 0
	_         [0]func()
}
