// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x8A0_1.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

// Group Kick Member
type OidbSvcTrpcTcp0X8A0_1 struct {
	GroupUin         uint32 `protobuf:"varint,1,opt"`
	TargetUid        string `protobuf:"bytes,3,opt"`
	RejectAddRequest bool   `protobuf:"varint,4,opt"`
	Field5           string `protobuf:"bytes,5,opt"`
	_                [0]func()
}

type OidbSvcTrpcTcp0X8A0_1Response struct {
	GroupUin uint32               `protobuf:"varint,1,opt"`
	ErrorMsg proto.Option[string] `protobuf:"bytes,2,opt"`
	_        [0]func()
}
