// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x89A_15.proto

package oidb

// Rename Group Title
type OidbSvcTrpcTcp0X89A_15 struct {
	GroupUin uint32                      `protobuf:"varint,1,opt"`
	Body     *OidbSvcTrpcTcp0X89A_15Body `protobuf:"bytes,2,opt"`
	_        [0]func()
}

type OidbSvcTrpcTcp0X89A_15Body struct {
	TargetName string `protobuf:"bytes,3,opt"`
	_          [0]func()
}
