// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0xED3_1.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

// Poke
type OidbSvcTrpcTcp0XED3_1 struct {
	Uin       uint32               `protobuf:"varint,1,opt"`
	GroupUin  uint32               `protobuf:"varint,2,opt"` // same when poke type is friend
	FriendUin uint32               `protobuf:"varint,5,opt"`
	Ext       proto.Option[uint32] `protobuf:"varint,6,opt"`
	_         [0]func()
}
