// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0xFE5_2.proto

package oidb

// Fetch Groups
type OidbSvcTrpcTcp0XFE5_2 struct {
	Config *OidbSvcTrpcTcp0XFE5_2Config `protobuf:"bytes,1,opt"`
	_      [0]func()
}

type OidbSvcTrpcTcp0XFE5_2Config struct {
	Config1 *OidbSvcTrpcTcp0XFE5_2Config1 `protobuf:"bytes,1,opt"`
	Config2 *OidbSvcTrpcTcp0XFE5_2Config2 `protobuf:"bytes,2,opt"`
	Config3 *OidbSvcTrpcTcp0XFE5_2Config3 `protobuf:"bytes,3,opt"`
	_       [0]func()
}

type OidbSvcTrpcTcp0XFE5_2Config1 struct {
	// all true
	GroupOwner  bool `protobuf:"varint,1,opt"`
	Field2      bool `protobuf:"varint,2,opt"`
	MemberMax   bool `protobuf:"varint,3,opt"`
	MemberCount bool `protobuf:"varint,4,opt"`
	GroupName   bool `protobuf:"varint,5,opt"`
	Field8      bool `protobuf:"varint,8,opt"`
	Field9      bool `protobuf:"varint,9,opt"`
	Field10     bool `protobuf:"varint,10,opt"`
	Field11     bool `protobuf:"varint,11,opt"`
	Field12     bool `protobuf:"varint,12,opt"`
	Field13     bool `protobuf:"varint,13,opt"`
	Field14     bool `protobuf:"varint,14,opt"`
	Field15     bool `protobuf:"varint,15,opt"`
	Field16     bool `protobuf:"varint,16,opt"`
	Field17     bool `protobuf:"varint,17,opt"`
	Field18     bool `protobuf:"varint,18,opt"`
	Question    bool `protobuf:"varint,19,opt"`
	Field20     bool `protobuf:"varint,20,opt"`
	Field22     bool `protobuf:"varint,22,opt"`
	Field23     bool `protobuf:"varint,23,opt"`
	Field24     bool `protobuf:"varint,24,opt"`
	Field25     bool `protobuf:"varint,25,opt"`
	Field26     bool `protobuf:"varint,26,opt"`
	Field27     bool `protobuf:"varint,27,opt"`
	Field28     bool `protobuf:"varint,28,opt"`
	Field29     bool `protobuf:"varint,29,opt"`
	Field30     bool `protobuf:"varint,30,opt"`
	Field31     bool `protobuf:"varint,31,opt"`
	Field32     bool `protobuf:"varint,32,opt"`
	Field5001   bool `protobuf:"varint,5001,opt"`
	Field5002   bool `protobuf:"varint,5002,opt"`
	Field5003   bool `protobuf:"varint,5003,opt"`
	_           [0]func()
}

type OidbSvcTrpcTcp0XFE5_2Config2 struct {
	// all ture
	Field1 bool `protobuf:"varint,1,opt"`
	Field2 bool `protobuf:"varint,2,opt"`
	Field3 bool `protobuf:"varint,3,opt"`
	Field4 bool `protobuf:"varint,4,opt"`
	Field5 bool `protobuf:"varint,5,opt"`
	Field6 bool `protobuf:"varint,6,opt"`
	Field7 bool `protobuf:"varint,7,opt"`
	Field8 bool `protobuf:"varint,8,opt"`
	_      [0]func()
}

type OidbSvcTrpcTcp0XFE5_2Config3 struct {
	Field5 bool `protobuf:"varint,5,opt"`
	Field6 bool `protobuf:"varint,6,opt"`
	_      [0]func()
}

type OidbSvcTrpcTcp0XFE5_2Response struct {
	Groups []*OidbSvcTrpcTcp0XFE5_2Group `protobuf:"bytes,2,rep"`
}

type OidbSvcTrpcTcp0XFE5_2Group struct {
	GroupUin uint32                          `protobuf:"varint,3,opt"`
	Info     *OidbSvcTrpcTcp0XFE5_2GroupInfo `protobuf:"bytes,4,opt"`
	_        [0]func()
}

type OidbSvcTrpcTcp0XFE5_2GroupInfo struct {
	GroupOwner  *OidbSvcTrpcTcp0XFE5_2Member `protobuf:"bytes,1,opt"`
	MemberMax   uint32                       `protobuf:"varint,3,opt"`
	MemberCount uint32                       `protobuf:"varint,4,opt"`
	GroupName   string                       `protobuf:"bytes,5,opt"`
	_           [0]func()
}

type OidbSvcTrpcTcp0XFE5_2Member struct {
	Uid string `protobuf:"bytes,2,opt"`
	_   [0]func()
}
