// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x5CF_11.proto

package oidb

// FetchFriendRequests
type OidbSvcTrpcTcp0X5CF_11 struct {
	Field1  int32  `protobuf:"varint,1,opt"` // 1
	Field3  int32  `protobuf:"varint,3,opt"` // 6
	SelfUid string `protobuf:"bytes,4,opt"`
	Field5  int32  `protobuf:"varint,5,opt"`  // 0
	Field6  int32  `protobuf:"varint,6,opt"`  // 80
	Field8  int32  `protobuf:"varint,8,opt"`  // 2
	Field9  int32  `protobuf:"varint,9,opt"`  // 0
	Field12 int32  `protobuf:"varint,12,opt"` // 1
	Field22 int32  `protobuf:"varint,22,opt"` //1
	_       [0]func()
}
