// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x972_6.proto

package oidb

// RequestFriendSearch
type OidbSvcTrpcTcp0X972_6 struct {
	TargetUin string                         `protobuf:"bytes,1,opt"`
	Settings  *OidbSvcTrpcTcp0X972_6Settings `protobuf:"bytes,3,opt"`
	_         [0]func()
}

type OidbSvcTrpcTcp0X972_6Settings struct {
	Field4  uint32 `protobuf:"varint,4,opt"` // 25
	Field11 string `protobuf:"bytes,11,opt"` // ""
	Setting string `protobuf:"bytes,55,opt"` // {"search_by_uid":true, "scenario":"related_people_and_groups_panel"}
	_       [0]func()
}
