// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x89E_0.proto

package oidb

// GroupTransfer
type OidbSvcTrpcTcp0X89E_0 struct {
	GroupUin  uint32 `protobuf:"varint,1,opt"`
	SourceUid string `protobuf:"bytes,2,opt"`
	TargetUid string `protobuf:"bytes,3,opt"`
	_         [0]func()
}
