// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/action/action.proto

package action

import (
	proto "github.com/RomiChan/protobuf/proto"

	message "github.com/LagrangeDev/LagrangeGo/client/packets/pb/message"
)

type FaceRoamRequest struct {
	Comm    *PlatInfo `protobuf:"bytes,1,opt"`
	SelfUin uint32    `protobuf:"varint,2,opt"`
	SubCmd  uint32    `protobuf:"varint,3,opt"` // 1
	Field6  uint32    `protobuf:"varint,6,opt"` // 1
	_       [0]func()
}

type PlatInfo struct {
	ImPlat    uint32               `protobuf:"varint,1,opt"`
	OSVersion proto.Option[string] `protobuf:"bytes,2,opt"`
	QVersion  proto.Option[string] `protobuf:"bytes,3,opt"`
	_         [0]func()
}

type FaceRoamResponse struct {
	RetCode  uint32            `protobuf:"varint,1,opt"`
	ErrMsg   string            `protobuf:"bytes,2,opt"`
	SubCmd   uint32            `protobuf:"varint,3,opt"`
	UserInfo *FaceRoamUserInfo `protobuf:"bytes,6,opt"`
	_        [0]func()
}

type FaceRoamUserInfo struct {
	FileName    []string `protobuf:"bytes,1,rep"`
	DeleteFile  []string `protobuf:"bytes,2,rep"`
	Bid         string   `protobuf:"bytes,3,opt"`
	MaxRoamSize uint32   `protobuf:"varint,4,opt"`
	EmojiType   []uint32 `protobuf:"varint,5,rep"`
}

type SendMessageRequest struct {
	State          int32                   `protobuf:"varint,1,opt"`
	SizeCache      int32                   `protobuf:"varint,2,opt"`
	UnknownFields  []byte                  `protobuf:"bytes,3,opt"`
	RoutingHead    *message.RoutingHead    `protobuf:"bytes,4,opt"`
	ContentHead    *message.ContentHead    `protobuf:"bytes,5,opt"`
	MessageBody    *message.MessageBody    `protobuf:"bytes,6,opt"`
	MsgSeq         int32                   `protobuf:"varint,7,opt"`
	MsgRand        int32                   `protobuf:"varint,8,opt"`
	SyncCookie     []byte                  `protobuf:"bytes,9,opt"`
	MsgVia         int32                   `protobuf:"varint,10,opt"`
	DataStatist    int32                   `protobuf:"varint,11,opt"`
	MessageControl *message.MessageControl `protobuf:"bytes,12,opt"`
	MultiSendSeq   int32                   `protobuf:"varint,13,opt"`
}

type SendMessageResponse struct {
	Result          int32                `protobuf:"varint,1,opt"`
	ErrMsg          proto.Option[string] `protobuf:"bytes,2,opt"`
	Timestamp1      uint32               `protobuf:"varint,3,opt"`
	Field10         uint32               `protobuf:"varint,10,opt"`
	GroupSequence   proto.Option[uint32] `protobuf:"varint,11,opt"`
	Timestamp2      uint32               `protobuf:"varint,12,opt"`
	PrivateSequence uint32               `protobuf:"varint,14,opt"`
	_               [0]func()
}

type SetStatus struct {
	Status        uint32              `protobuf:"varint,1,opt"`
	ExtStatus     uint32              `protobuf:"varint,2,opt"`
	BatteryStatus uint32              `protobuf:"varint,3,opt"` // 电量百分比
	CustomExt     *SetStatusCustomExt `protobuf:"bytes,4,opt"`
	_             [0]func()
}

type SetStatusCustomExt struct {
	FaceId uint32               `protobuf:"varint,1,opt"`
	Text   proto.Option[string] `protobuf:"bytes,2,opt"`
	Field3 uint32               `protobuf:"varint,3,opt"`
	_      [0]func()
}

type SetStatusResponse struct {
	Message string `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type HttpConn struct {
	Field1       int32   `protobuf:"varint,1,opt"`  // 0
	Field2       int32   `protobuf:"varint,2,opt"`  // 0
	Field3       int32   `protobuf:"varint,3,opt"`  // 16
	Field4       int32   `protobuf:"varint,4,opt"`  // 1
	Tgt          string  `protobuf:"bytes,5,opt"`   // tgt lower hex
	Field6       int32   `protobuf:"varint,6,opt"`  // 3
	ServiceTypes []int32 `protobuf:"varint,7,rep"`  // 1, 5, 10, 21 for image
	Field9       int32   `protobuf:"varint,9,opt"`  // 2
	Field10      int32   `protobuf:"varint,10,opt"` // 9
	Field11      int32   `protobuf:"varint,11,opt"` // 8
	Ver          string  `protobuf:"bytes,15,opt"`  // 1.0.1
}

type HttpConn0X6Ff_501 struct {
	HttpConn *HttpConn `protobuf:"bytes,1281,opt"`
	_        [0]func()
}

type HttpConn0X6Ff_501Response struct {
	HttpConn *HttpConnResponse `protobuf:"bytes,1281,opt"`
	_        [0]func()
}

type HttpConnResponse struct {
	SigSession  []byte        `protobuf:"bytes,1,opt"`
	SessionKey  []byte        `protobuf:"bytes,2,opt"`
	ServerInfos []*ServerInfo `protobuf:"bytes,3,rep"`
}

type ServerAddr struct {
	Type uint32 `protobuf:"varint,1,opt"`
	IP   uint32 `protobuf:"fixed32,2,opt"`
	Port uint32 `protobuf:"varint,3,opt"`
	Area uint32 `protobuf:"varint,4,opt"`
	_    [0]func()
}

type ServerInfo struct {
	ServiceType uint32        `protobuf:"varint,1,opt"`
	ServerAddrs []*ServerAddr `protobuf:"bytes,2,rep"`
}
