// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/tlv543.proto

package pb

type Tlv543 struct {
	Layer1 *Tlv543Layer1 `protobuf:"bytes,9,opt"`
	_      [0]func()
}

type Tlv543Layer1 struct {
	Layer2 *Tlv543Layer2 `protobuf:"bytes,11,opt"`
	_      [0]func()
}

type Tlv543Layer2 struct {
	Uid string `protobuf:"bytes,1,opt"`
	_   [0]func()
}
