// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/service.proto

package service

type InfoPushGroup struct {
	GroupUin    uint32 `protobuf:"varint,1,opt"`
	Sequence1   uint32 `protobuf:"varint,2,opt"`
	Sequence2   uint32 `protobuf:"varint,3,opt"`
	Field4      uint32 `protobuf:"varint,4,opt"`
	LastMsgTime uint32 `protobuf:"varint,8,opt"`
	GroupName   string `protobuf:"bytes,9,opt"`
	Sequence3   uint32 `protobuf:"varint,10,opt"`
	Random      uint64 `protobuf:"varint,11,opt"`
	Field13     uint32 `protobuf:"varint,13,opt"`
	_           [0]func()
}
