// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/album/QunMedia_GetMediaList.proto

package album

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type QzoneGetMediaList struct {
	Field1       uint32                 `protobuf:"varint,1,opt"`
	Field2       string                 `protobuf:"bytes,2,opt"`
	Field3       string                 `protobuf:"bytes,3,opt"`
	Field4       *QzoneGetMediaList_F4  `protobuf:"bytes,4,opt"`
	UinTimeStamp string                 `protobuf:"bytes,5,opt"`
	Field10      *QzoneGetMediaList_F10 `protobuf:"bytes,10,opt"`
	_            [0]func()
}

type QzoneGetMediaList_F4 struct {
	GroupID  string `protobuf:"bytes,1,opt"`
	AlbumID  string `protobuf:"bytes,2,opt"`
	Field3   uint32 `protobuf:"varint,3,opt"`
	Field4   string `protobuf:"bytes,4,opt"`
	PageInfo string `protobuf:"bytes,5,opt"`
	_        [0]func()
}

type QzoneGetMediaList_F10 struct {
	AppIdFlag  string `protobuf:"bytes,1,opt"`
	AppIdValue string `protobuf:"bytes,2,opt"`
	_          [0]func()
}

type QzoneGetMediaList_Response struct {
	Field1    proto.Option[uint32]             `protobuf:"varint,1,opt"`
	ErrorCode proto.Option[uint32]             `protobuf:"varint,2,opt"`
	ErrorMsg  proto.Option[string]             `protobuf:"bytes,3,opt"`
	Body      *QzoneGetMediaList_Response_Body `protobuf:"bytes,4,opt"`
	_         [0]func()
}

type QzoneGetMediaList_Response_Body struct {
	AlbumInfo    *AlbumInfo           `protobuf:"bytes,1,opt"`
	ElemMetaInfo []*AlbumElemMetaInfo `protobuf:"bytes,2,rep"`
	ElemInfo     []*AlbumElemInfo     `protobuf:"bytes,3,rep"`
	PageInfo     proto.Option[string] `protobuf:"bytes,5,opt"`
}

type AlbumInfo struct {
	AlbumID        string          `protobuf:"bytes,1,opt"`
	AlbumName      string          `protobuf:"bytes,3,opt"`
	CreateTime     uint32          `protobuf:"varint,5,opt"`
	LastModifyTime uint32          `protobuf:"varint,6,opt"`
	LastUploadTime uint32          `protobuf:"varint,7,opt"`
	Count          uint32          `protobuf:"varint,8,opt"`
	ThumbInfo      *AlbumThumbInfo `protobuf:"bytes,9,opt"`
	CreatorInfo    *UserInfo       `protobuf:"bytes,10,opt"`
	_              [0]func()
}

type AlbumThumbInfo struct {
	ThumbImageInfo *AlbumThumbImageInfo `protobuf:"bytes,2,opt"`
	_              [0]func()
}

type AlbumThumbImageInfo struct {
	ImageID      string                         `protobuf:"bytes,3,opt"`
	ImgLinkInfos []*AlbumElemImgLinkComplexInfo `protobuf:"bytes,4,rep"`
	ImgLinkInfo  *AlbumElemImgLinkInfo          `protobuf:"bytes,5,opt"`
}

type AlbumElemMetaInfo struct {
	UploadTimeStamp uint32    `protobuf:"varint,1,opt"`
	UploadDate      string    `protobuf:"bytes,3,opt"`
	UploaderInfo    *UserInfo `protobuf:"bytes,4,opt"`
	_               [0]func()
}

type AlbumElemInfo struct {
	ImgInfo        *AlbumElemImgInfo   `protobuf:"bytes,2,opt"`
	VideoInfo      *AlbumElemVideoInfo `protobuf:"bytes,3,opt"`
	UploaderUin    string              `protobuf:"bytes,4,opt"`
	LastModifyTime uint32              `protobuf:"varint,7,opt"`
	LastUploadTime uint32              `protobuf:"varint,8,opt"`
	UploaderInfo   *UserInfo           `protobuf:"bytes,12,opt"`
	_              [0]func()
}

type AlbumElemImgInfo struct {
	FileName     string                         `protobuf:"bytes,1,opt"`
	ImageID      string                         `protobuf:"bytes,3,opt"`
	ImgLinkInfos []*AlbumElemImgLinkComplexInfo `protobuf:"bytes,4,rep"`
	ImgLinkInfo  *AlbumElemImgLinkInfo          `protobuf:"bytes,5,opt"`
}

type AlbumElemImgLinkComplexInfo struct {
	Seq         uint32                `protobuf:"varint,1,opt"`
	ImgLinkInfo *AlbumElemImgLinkInfo `protobuf:"bytes,2,opt"`
	_           [0]func()
}

type AlbumElemImgLinkInfo struct {
	ImageURL string `protobuf:"bytes,1,opt"`
	Height   uint32 `protobuf:"varint,2,opt"`
	Width    uint32 `protobuf:"varint,3,opt"`
	_        [0]func()
}

type AlbumElemVideoInfo struct {
	VideoID             string                       `protobuf:"bytes,1,opt"`
	VideoURL            string                       `protobuf:"bytes,2,opt"`
	VideoMetaInfo       *AlbumElemVideoMetaInfo      `protobuf:"bytes,3,opt"`
	VideoHeight         uint32                       `protobuf:"varint,4,opt"`
	VideoWidth          uint32                       `protobuf:"varint,5,opt"`
	VideoThumbImageInfo *AlbumElemImgLinkComplexInfo `protobuf:"bytes,7,opt"`
	_                   [0]func()
}

type AlbumElemVideoMetaInfo struct {
	VideoName            string                         `protobuf:"bytes,1,opt"`
	VideoThumbImageID    string                         `protobuf:"bytes,3,opt"`
	VideoThumbImageInfos []*AlbumElemImgLinkComplexInfo `protobuf:"bytes,4,rep"`
	VideoThumbImageInfo  *AlbumElemImgLinkInfo          `protobuf:"bytes,5,opt"`
}

type UserInfo struct {
	UserNickName string `protobuf:"bytes,2,opt"`
	UserUin      string `protobuf:"bytes,13,opt"`
	_            [0]func()
}
