// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/status/group.proto

package status

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type MemberChanged struct {
	Uin         uint32               `protobuf:"varint,1,opt"`
	Uid         string               `protobuf:"bytes,3,opt"`
	ExitType    proto.Option[int32]  `protobuf:"varint,4,opt"` // 131 kick 130 exit
	OperatorUid proto.Option[string] `protobuf:"bytes,5,opt"`
	JoinType    proto.Option[int32]  `protobuf:"varint,6,opt"` // 6 scan qr
	_           [0]func()
}

type MemberJoinRequest struct {
	GroupID      uint32               `protobuf:"varint,1,opt"`
	Uid          string               `protobuf:"bytes,3,opt"`
	Src          int32                `protobuf:"varint,4,opt"`
	RequestField proto.Option[string] `protobuf:"bytes,5,opt"`
	Field9       []byte               `protobuf:"bytes,9,opt"`
}

type InviteInner struct {
	GroupID    uint32 `protobuf:"varint,1,opt"`
	Uid        string `protobuf:"bytes,5,opt"`
	InvitorUid string `protobuf:"bytes,6,opt"`
	_          [0]func()
}

type InviteInfo struct {
	Inner *InviteInner `protobuf:"bytes,1,opt"`
	_     [0]func()
}

type MemberInviteRequest struct {
	Cmd  int32       `protobuf:"varint,1,opt"`
	Info *InviteInfo `protobuf:"bytes,2,opt"`
	_    [0]func()
}
