// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/system/system.proto

package system

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type NTDeviceSign struct {
	Trace string               `protobuf:"bytes,15,opt"`
	Uid   proto.Option[string] `protobuf:"bytes,16,opt"`
	Sign  *Sign                `protobuf:"bytes,24,opt"`
	_     [0]func()
}

type Sign struct {
	Signature []byte               `protobuf:"bytes,1,opt"`
	Token     proto.Option[string] `protobuf:"bytes,2,opt"`
	S         *Software            `protobuf:"bytes,3,opt"`
}

type Software struct {
	Ver   string               `protobuf:"bytes,2,opt"`
	Token proto.Option[string] `protobuf:"bytes,3,opt"`
	_     [0]func()
}

type NTOS struct {
	OS   string `protobuf:"bytes,1,opt"`
	Name string `protobuf:"bytes,2,opt"`
	_    [0]func()
}

type NTPacketUid struct {
	Uid proto.Option[string] `protobuf:"bytes,16,opt"`
	_   [0]func()
}

type NTSsoHeartBeat struct {
	Type int32 `protobuf:"varint,1,opt"`
	_    [0]func()
}

type NTSysEvent struct {
	IP  string         `protobuf:"bytes,1,opt"`
	Sid int64          `protobuf:"varint,2,opt"`
	Sub *NTSysEventSub `protobuf:"bytes,3,opt"`
	_   [0]func()
}

type NTSysEventSub struct {
	State    int64  `protobuf:"varint,2,opt"`
	Field3   int32  `protobuf:"varint,3,opt"`
	Field4   int64  `protobuf:"varint,4,opt"`
	Uin      int64  `protobuf:"varint,5,opt"`
	Flag     int32  `protobuf:"varint,6,opt"`
	On       int32  `protobuf:"varint,7,opt"`
	GroupUin uint32 `protobuf:"varint,8,opt"`
	_        [0]func()
}

type OnlineOsInfo struct {
	User       string               `protobuf:"bytes,1,opt"`
	OS         string               `protobuf:"bytes,2,opt"`
	OSVer      string               `protobuf:"bytes,3,opt"`
	VendorName proto.Option[string] `protobuf:"bytes,4,opt"`
	OSLower    string               `protobuf:"bytes,5,opt"`
	_          [0]func()
}

type ServiceKickNTResponse struct {
	Uin    uint32 `protobuf:"varint,1,opt"`
	Tips   string `protobuf:"bytes,3,opt"`
	Title  string `protobuf:"bytes,4,opt"`
	Field5 int32  `protobuf:"varint,5,opt"`
	Field6 int32  `protobuf:"varint,6,opt"`
	Field8 int32  `protobuf:"varint,8,opt"`
	_      [0]func()
}

type ServiceRegister struct {
	Guid               proto.Option[string] `protobuf:"bytes,1,opt"`
	Type               proto.Option[int32]  `protobuf:"varint,2,opt"`
	CurrentVersion     proto.Option[string] `protobuf:"bytes,3,opt"`
	Field4             proto.Option[int32]  `protobuf:"varint,4,opt"`
	LocaleId           proto.Option[int32]  `protobuf:"varint,5,opt"` // 2052
	Online             *OnlineOsInfo        `protobuf:"bytes,6,opt"`
	SetMute            proto.Option[int32]  `protobuf:"varint,7,opt"`
	RegisterVendorType proto.Option[int32]  `protobuf:"varint,8,opt"`
	RegType            proto.Option[int32]  `protobuf:"varint,9,opt"`
	_                  [0]func()
}

type ServiceRegisterResponse struct {
	Message   proto.Option[string] `protobuf:"bytes,2,opt"`
	Timestamp uint32               `protobuf:"varint,3,opt"`
	Field4    int32                `protobuf:"varint,4,opt"`
	Field5    int32                `protobuf:"varint,5,opt"`
	_         [0]func()
}
