// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/message/action.proto

package message

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type LongMsgResult struct {
	Action *LongMsgAction `protobuf:"bytes,2,opt"`
	_      [0]func()
}

type LongMsgAction struct {
	ActionCommand string          `protobuf:"bytes,1,opt"`
	ActionData    *LongMsgContent `protobuf:"bytes,2,opt"`
	_             [0]func()
}

type LongMsgContent struct {
	MsgBody []*PushMsgBody `protobuf:"bytes,1,rep"`
}

// trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg Request
type RecvLongMsgReq struct {
	Info     *RecvLongMsgInfo `protobuf:"bytes,1,opt"`
	Settings *LongMsgSettings `protobuf:"bytes,15,opt"`
	_        [0]func()
}

type RecvLongMsgInfo struct {
	Uid     *LongMsgUid          `protobuf:"bytes,1,opt"`
	ResId   proto.Option[string] `protobuf:"bytes,2,opt"`
	Acquire bool                 `protobuf:"varint,3,opt"`
	_       [0]func()
}

type LongMsgUid struct {
	Uid proto.Option[string] `protobuf:"bytes,2,opt"`
	_   [0]func()
}

type LongMsgSettings struct {
	Field1 uint32 `protobuf:"varint,1,opt"` // 4
	Field2 uint32 `protobuf:"varint,2,opt"` // 1
	Field3 uint32 `protobuf:"varint,3,opt"` // 7
	Field4 uint32 `protobuf:"varint,4,opt"` // 0
	_      [0]func()
}

type RecvLongMsgResp struct {
	Result   *RecvLongMsgResult `protobuf:"bytes,1,opt"`
	Settings *LongMsgSettings   `protobuf:"bytes,15,opt"`
	_        [0]func()
}

type RecvLongMsgResult struct {
	ResId   string `protobuf:"bytes,3,opt"`
	Payload []byte `protobuf:"bytes,4,opt"`
}

type SendLongMsgReq struct {
	Info     *SendLongMsgInfo `protobuf:"bytes,2,opt"`
	Settings *LongMsgSettings `protobuf:"bytes,15,opt"`
	_        [0]func()
}

type SendLongMsgInfo struct {
	Type     uint32               `protobuf:"varint,1,opt"` // Group: 3, Friend: 1
	Uid      *LongMsgUid          `protobuf:"bytes,2,opt"`
	GroupUin proto.Option[uint32] `protobuf:"varint,3,opt"`
	Payload  []byte               `protobuf:"bytes,4,opt"`
}

type SendLongMsgResp struct {
	Result   *SendLongMsgResult `protobuf:"bytes,2,opt"`
	Settings *LongMsgSettings   `protobuf:"bytes,15,opt"`
	_        [0]func()
}

type SendLongMsgResult struct {
	ResId string `protobuf:"bytes,3,opt"`
	_     [0]func()
}

type SsoGetGroupMsg struct {
	Info      *SsoGetGroupMsgInfo `protobuf:"bytes,1,opt"`
	Direction bool                `protobuf:"varint,2,opt"`
	_         [0]func()
}

type SsoGetGroupMsgInfo struct {
	GroupUin      uint32 `protobuf:"varint,1,opt"`
	StartSequence uint32 `protobuf:"varint,2,opt"`
	EndSequence   uint32 `protobuf:"varint,3,opt"`
	_             [0]func()
}

type SsoGetGroupMsgResponse struct {
	Body *SsoGetGroupMsgResponseBody `protobuf:"bytes,3,opt"`
	_    [0]func()
}

type SsoGetGroupMsgResponseBody struct {
	GroupUin      uint32         `protobuf:"varint,3,opt"`
	StartSequence uint32         `protobuf:"varint,4,opt"`
	EndSequence   uint32         `protobuf:"varint,5,opt"`
	Messages      []*PushMsgBody `protobuf:"bytes,6,rep"`
}

type SsoGetRoamMsg struct {
	FriendUid proto.Option[string] `protobuf:"bytes,1,opt"`
	Time      uint32               `protobuf:"varint,2,opt"`
	Random    uint32               `protobuf:"varint,3,opt"` // 0
	Count     uint32               `protobuf:"varint,4,opt"`
	Direction bool                 `protobuf:"varint,5,opt"` // true
	_         [0]func()
}

type SsoGetRoamMsgResponse struct {
	FriendUid string         `protobuf:"bytes,3,opt"`
	Timestamp uint32         `protobuf:"varint,5,opt"`
	Random    uint32         `protobuf:"varint,6,opt"`
	Messages  []*PushMsgBody `protobuf:"bytes,7,rep"`
}
