// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/message/c2c.proto

package message

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type C2C struct {
	Uin         proto.Option[uint32] `protobuf:"varint,1,opt"`
	Uid         proto.Option[string] `protobuf:"bytes,2,opt"`
	Field3      proto.Option[uint32] `protobuf:"varint,3,opt"`
	Sig         proto.Option[uint32] `protobuf:"varint,4,opt"`
	ReceiverUin proto.Option[uint32] `protobuf:"varint,5,opt"`
	ReceiverUid proto.Option[string] `protobuf:"bytes,6,opt"`
	_           [0]func()
}
