// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/service/oidb/OidbSvcTrpcTcp0x102A_0.proto

package oidb

// Get Cookie
type OidbSvcTrpcTcp0X102A_0 struct {
	Domain []string `protobuf:"bytes,1,rep"`
}

type OidbSvcTrpcTcp0X102A_0Response struct {
	Urls []*OidbProperty `protobuf:"bytes,1,rep"`
}
