// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/login/ecdh.proto

package login

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type SsoKeyExchange struct {
	PubKey    []byte `protobuf:"bytes,1,opt"`
	Type      int32  `protobuf:"varint,2,opt"`
	GcmCalc1  []byte `protobuf:"bytes,3,opt"`
	Timestamp uint32 `protobuf:"varint,4,opt"`
	GcmCalc2  []byte `protobuf:"bytes,5,opt"`
}

type SsoKeyExchangeResponse struct {
	GcmEncrypted []byte `protobuf:"bytes,1,opt"`
	Body         []byte `protobuf:"bytes,2,opt"`
	PublicKey    []byte `protobuf:"bytes,3,opt"`
}

type SsoKeyExchangeDecrypted struct {
	GcmKey     []byte `protobuf:"bytes,1,opt"`
	Sign       []byte `protobuf:"bytes,2,opt"`
	Expiration uint32 `protobuf:"varint,3,opt"`
}

type SsoKeyExchangePlain struct {
	Uin  proto.Option[string] `protobuf:"bytes,1,opt"`
	Guid []byte               `protobuf:"bytes,2,opt"`
}
