on:
  push:
    branches:
      - 'master'
    paths:
      - '**.go'
      - 'go.mod'
      - '**.yml'

name: ci

env:
  GO111MODULE: on

jobs:
  ci:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false

      - name: Sort Imports
        run: |
          export PATH="$PATH:$GOPATH/bin"
          go install github.com/incu6us/goimports-reviser@latest
          pwd
          find . -name "*.go" | xargs -I {} goimports-reviser -file-path {} -project-name "github.com/LagraneDev/LagrangeGo"

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: 'v1.61.0'
          args: '--timeout 9999s'
          only-new-issues: true
          skip-save-cache: true

      - name: commit back
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "ci(chore): Fix stylings"
          git push


