on:
  push:
    branches:
      - 'master'
    paths:
      - '**.go'
      - 'go.mod'
      - '**.yml'

name: commitback

env:
  GO111MODULE: on

jobs:
  commitback:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: false

      - name: Sort Imports
        run: |
          export PATH="$PATH:$GOPATH/bin"
          go install -v github.com/incu6us/goimports-reviser/v3@latest
          make sort

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1
          args: '--timeout 9999s'
          only-new-issues: true
          skip-save-cache: true

      - name: commit back
        if: github.repository_owner == 'LagrangeDev'
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "ci(chore): Fix stylings"
          git push
